---
apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: example
  labels:
    example: "true"
  annotations:
    crossplane.io/external-name: crossplane-example-bucket
spec:
  location: US
  storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: gcp-provider
  deletionPolicy: Delete