---
# Put your rbac rules here
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cache.crossplane.io
  - compute.crossplane.io
  - database.crossplane.io
  - core.crossplane.io
  - storage.crossplane.io
  - gcp.crossplane.io
  - cache.gcp.crossplane.io
  - compute.gcp.crossplane.io
  - database.gcp.crossplane.io
  - servicenetworking.gcp.crossplane.io
  - storage.gcp.crossplane.io
  - workload.crossplane.io
  resources:
  - "*"
  verbs:
  - "*"
